spring.application.name=LeetAiBackend
server.port=8080

# External APIs
leetcode.api.baseurl=https://alfa-leetcode-api.onrender.com
groq.api.baseurl=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY:mock}
